# Generated by Django 6.1.2 on 2026-10-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(default='', max_length=240)),
                ('category', models.CharField(default='Full-Stack', max_length=120)),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('in_progress', 'In Development'), ('planned', 'Planned')], default='implemented', max_length=20)),
                ('description', models.TextField(default='')),
                ('problem', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('role', models.CharField(default='', max_length=240)),
                ('architecture', models.TextField(blank=True, default='', help_text='Explain the system architecture: frontend, API, backend, database and data flow.')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('github_url', models.URLField(blank=True, default='')),
                ('demo_url', models.URLField(blank=True, default='')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('started_at', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(default='tools', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture_text', models.TextField(blank=True, default='')),
                ('challenges', models.JSONField(blank=True, default=list, help_text='List of strings / objects.')),
                ('solutions', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('lessons', models.JSONField(blank=True, default=list)),
                ('decisions', models.JSONField(blank=True, default=list, help_text='Key architectural decisions.')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('in_progress', 'In Development'), ('planned', 'Planned')], default='implemented', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_uses', to='projects.technology')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'technology')},
            },
        ),
    ]
