# Generated by Django 6.1.2 on 2026-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.CharField(blank=True, default='', max_length=40)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.CharField(default='', max_length=40)),
                ('end_date', models.CharField(blank=True, default='', max_length=40)),
                ('current', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('employment_type', models.CharField(blank=True, default='', max_length=60)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('start_date', models.CharField(default='', max_length=40)),
                ('end_date', models.CharField(blank=True, default='', max_length=40)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(default='', help_text='Line-separated bullet points.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lenox Okoth', max_length=120)),
                ('title', models.CharField(default='Full-Stack Software Engineer', max_length=160)),
                ('brand', models.CharField(default='Lentech', max_length=80)),
                ('role_tagline', models.CharField(default='', max_length=240)),
                ('summary', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('location', models.CharField(default='Kenya', max_length=160)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('photo', models.CharField(blank=True, default='', help_text='Public URL of the profile photo.', max_length=500)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=160)),
                ('meta_description', models.CharField(blank=True, default='', max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('mobile', 'Mobile'), ('tools', 'Tools'), ('engineering', 'Engineering'), ('other', 'Other')], max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
