# Generated by Django 6.1.2 on 2026-10-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('website', models.URLField(blank=True, default='')),
                ('references_note', models.CharField(blank=True, default='References available on request.', max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('target_role', models.CharField(blank=True, default='', max_length=160)),
                ('summary', models.TextField(blank=True, default='', help_text='Overrides the base resume summary.')),
                ('emphasis', models.JSONField(blank=True, default=list, help_text='List of skill names to list first, e.g. ["React", "Django", "PostgreSQL"].')),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('summary', 'Summary'), ('skills', 'Skills'), ('experience', 'Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('projects', 'Projects'), ('links', 'Links')], max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Optional {include:[ids], order:[ids]} filters.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume.resume')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume.resumeversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
